package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucVaiTroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucVaiTroAllPropertiesEquals(DanhMucVaiTro expected, DanhMucVaiTro actual) {
        assertDanhMucVaiTroAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucVaiTroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucVaiTroAllUpdatablePropertiesEquals(DanhMucVaiTro expected, DanhMucVaiTro actual) {
        assertDanhMucVaiTroUpdatableFieldsEquals(expected, actual);
        assertDanhMucVaiTroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucVaiTroAutoGeneratedPropertiesEquals(DanhMucVaiTro expected, DanhMucVaiTro actual) {
        assertThat(expected)
            .as("Verify DanhMucVaiTro auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucVaiTroUpdatableFieldsEquals(DanhMucVaiTro expected, DanhMucVaiTro actual) {
        assertThat(expected)
            .as("Verify DanhMucVaiTro relevant properties")
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getIdLoaiHopDong()).as("check idLoaiHopDong").isEqualTo(actual.getIdLoaiHopDong()))
            .satisfies(e -> assertThat(e.getIdLoaiVaiTro()).as("check idLoaiVaiTro").isEqualTo(actual.getIdLoaiVaiTro()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucVaiTroUpdatableRelationshipsEquals(DanhMucVaiTro expected, DanhMucVaiTro actual) {
        // empty method
    }
}
