package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhSachChungThucAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachChungThucAllPropertiesEquals(DanhSachChungThuc expected, DanhSachChungThuc actual) {
        assertDanhSachChungThucAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhSachChungThucAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachChungThucAllUpdatablePropertiesEquals(DanhSachChungThuc expected, DanhSachChungThuc actual) {
        assertDanhSachChungThucUpdatableFieldsEquals(expected, actual);
        assertDanhSachChungThucUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachChungThucAutoGeneratedPropertiesEquals(DanhSachChungThuc expected, DanhSachChungThuc actual) {
        assertThat(expected)
            .as("Verify DanhSachChungThuc auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachChungThucUpdatableFieldsEquals(DanhSachChungThuc expected, DanhSachChungThuc actual) {
        assertThat(expected)
            .as("Verify DanhSachChungThuc relevant properties")
            .satisfies(e -> assertThat(e.getIdDonVi()).as("check idDonVi").isEqualTo(actual.getIdDonVi()))
            .satisfies(e -> assertThat(e.getNguoiChungThuc()).as("check nguoiChungThuc").isEqualTo(actual.getNguoiChungThuc()))
            .satisfies(e -> assertThat(e.getNguoiThaoTac()).as("check nguoiThaoTac").isEqualTo(actual.getNguoiThaoTac()))
            .satisfies(e -> assertThat(e.getNgayChungThuc()).as("check ngayChungThuc").isEqualTo(actual.getNgayChungThuc()))
            .satisfies(e -> assertThat(e.getNgayThaoTac()).as("check ngayThaoTac").isEqualTo(actual.getNgayThaoTac()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()))
            .satisfies(e -> assertThat(e.getQuyenSo()).as("check quyenSo").isEqualTo(actual.getQuyenSo()))
            .satisfies(e -> assertThat(e.getSrcChungThuc()).as("check srcChungThuc").isEqualTo(actual.getSrcChungThuc()))
            .satisfies(e -> assertThat(e.getChuKyNgoaiTruSo()).as("check chuKyNgoaiTruSo").isEqualTo(actual.getChuKyNgoaiTruSo()))
            .satisfies(e -> assertThat(e.getNgayText()).as("check ngayText").isEqualTo(actual.getNgayText()))
            .satisfies(e -> assertThat(e.getStrSearch()).as("check strSearch").isEqualTo(actual.getStrSearch()))
            .satisfies(e -> assertThat(e.getSoTienThu()).as("check soTienThu").isEqualTo(actual.getSoTienThu()))
            .satisfies(e -> assertThat(e.getLdPheDuyet()).as("check ldPheDuyet").isEqualTo(actual.getLdPheDuyet()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachChungThucUpdatableRelationshipsEquals(DanhSachChungThuc expected, DanhSachChungThuc actual) {
        assertThat(expected)
            .as("Verify DanhSachChungThuc relationships")
            .satisfies(e ->
                assertThat(e.getDanhMucLoaiGiayToChungThuc())
                    .as("check danhMucLoaiGiayToChungThuc")
                    .isEqualTo(actual.getDanhMucLoaiGiayToChungThuc())
            );
    }
}
