package vn.vnpt.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class HopDongCongChungTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static HopDongCongChung getHopDongCongChungSample1() {
        return new HopDongCongChung()
            .id("id1")
            .nguoiLapHd(1L)
            .thongTinDuongSu("thongTinDuongSu1")
            .thongTinTaiSan("thongTinTaiSan1")
            .thongTinVanBan("thongTinVanBan1")
            .trangThai(1L)
            .idLoaiHd("idLoaiHd1")
            .dieuKhoanHd("dieuKhoanHd1")
            .idDonVi(1L)
            .nguoiThaoTac(1L)
            .idHdGoc("idHdGoc1")
            .thongTinChuyenNhuong("thongTinChuyenNhuong1")
            .maHopDong("maHopDong1")
            .srcHopDong("srcHopDong1")
            .idSoCongChung("idSoCongChung1")
            .soCongChung("soCongChung1")
            .congChungVien(1L)
            .nguoiRutTrich(1L)
            .soTienRutTrich(1L)
            .hdThuCong(1L)
            .trangThaiRutTrich(1L)
            .chuKyNgoaiTruSo(1L)
            .strSearch("strSearch1")
            .idMaster(1L)
            .idHdSdHb(1L)
            .srcDmMaster("srcDmMaster1")
            .repRefUnique(1L)
            .ngayText("ngayText1")
            .ngayNum(1L)
            .thuLaoCongChung(1L)
            .quyenLaiSt("quyenLaiSt1")
            .soLaiSt("soLaiSt1")
            .quyenLaiTl("quyenLaiTl1")
            .soLaiTl("soLaiTl1")
            .srcKySoPdf("srcKySoPdf1")
            .srcKySoPdfSigned("srcKySoPdfSigned1")
            .syncStatus(1L)
            .ngayRutTrichText("ngayRutTrichText1");
    }

    public static HopDongCongChung getHopDongCongChungSample2() {
        return new HopDongCongChung()
            .id("id2")
            .nguoiLapHd(2L)
            .thongTinDuongSu("thongTinDuongSu2")
            .thongTinTaiSan("thongTinTaiSan2")
            .thongTinVanBan("thongTinVanBan2")
            .trangThai(2L)
            .idLoaiHd("idLoaiHd2")
            .dieuKhoanHd("dieuKhoanHd2")
            .idDonVi(2L)
            .nguoiThaoTac(2L)
            .idHdGoc("idHdGoc2")
            .thongTinChuyenNhuong("thongTinChuyenNhuong2")
            .maHopDong("maHopDong2")
            .srcHopDong("srcHopDong2")
            .idSoCongChung("idSoCongChung2")
            .soCongChung("soCongChung2")
            .congChungVien(2L)
            .nguoiRutTrich(2L)
            .soTienRutTrich(2L)
            .hdThuCong(2L)
            .trangThaiRutTrich(2L)
            .chuKyNgoaiTruSo(2L)
            .strSearch("strSearch2")
            .idMaster(2L)
            .idHdSdHb(2L)
            .srcDmMaster("srcDmMaster2")
            .repRefUnique(2L)
            .ngayText("ngayText2")
            .ngayNum(2L)
            .thuLaoCongChung(2L)
            .quyenLaiSt("quyenLaiSt2")
            .soLaiSt("soLaiSt2")
            .quyenLaiTl("quyenLaiTl2")
            .soLaiTl("soLaiTl2")
            .srcKySoPdf("srcKySoPdf2")
            .srcKySoPdfSigned("srcKySoPdfSigned2")
            .syncStatus(2L)
            .ngayRutTrichText("ngayRutTrichText2");
    }

    public static HopDongCongChung getHopDongCongChungRandomSampleGenerator() {
        return new HopDongCongChung()
            .id(UUID.randomUUID().toString())
            .nguoiLapHd(longCount.incrementAndGet())
            .thongTinDuongSu(UUID.randomUUID().toString())
            .thongTinTaiSan(UUID.randomUUID().toString())
            .thongTinVanBan(UUID.randomUUID().toString())
            .trangThai(longCount.incrementAndGet())
            .idLoaiHd(UUID.randomUUID().toString())
            .dieuKhoanHd(UUID.randomUUID().toString())
            .idDonVi(longCount.incrementAndGet())
            .nguoiThaoTac(longCount.incrementAndGet())
            .idHdGoc(UUID.randomUUID().toString())
            .thongTinChuyenNhuong(UUID.randomUUID().toString())
            .maHopDong(UUID.randomUUID().toString())
            .srcHopDong(UUID.randomUUID().toString())
            .idSoCongChung(UUID.randomUUID().toString())
            .soCongChung(UUID.randomUUID().toString())
            .congChungVien(longCount.incrementAndGet())
            .nguoiRutTrich(longCount.incrementAndGet())
            .soTienRutTrich(longCount.incrementAndGet())
            .hdThuCong(longCount.incrementAndGet())
            .trangThaiRutTrich(longCount.incrementAndGet())
            .chuKyNgoaiTruSo(longCount.incrementAndGet())
            .strSearch(UUID.randomUUID().toString())
            .idMaster(longCount.incrementAndGet())
            .idHdSdHb(longCount.incrementAndGet())
            .srcDmMaster(UUID.randomUUID().toString())
            .repRefUnique(longCount.incrementAndGet())
            .ngayText(UUID.randomUUID().toString())
            .ngayNum(longCount.incrementAndGet())
            .thuLaoCongChung(longCount.incrementAndGet())
            .quyenLaiSt(UUID.randomUUID().toString())
            .soLaiSt(UUID.randomUUID().toString())
            .quyenLaiTl(UUID.randomUUID().toString())
            .soLaiTl(UUID.randomUUID().toString())
            .srcKySoPdf(UUID.randomUUID().toString())
            .srcKySoPdfSigned(UUID.randomUUID().toString())
            .syncStatus(longCount.incrementAndGet())
            .ngayRutTrichText(UUID.randomUUID().toString());
    }
}
