package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HopDongCongChungAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHopDongCongChungAllPropertiesEquals(HopDongCongChung expected, HopDongCongChung actual) {
        assertHopDongCongChungAutoGeneratedPropertiesEquals(expected, actual);
        assertHopDongCongChungAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHopDongCongChungAllUpdatablePropertiesEquals(HopDongCongChung expected, HopDongCongChung actual) {
        assertHopDongCongChungUpdatableFieldsEquals(expected, actual);
        assertHopDongCongChungUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHopDongCongChungAutoGeneratedPropertiesEquals(HopDongCongChung expected, HopDongCongChung actual) {
        assertThat(expected)
            .as("Verify HopDongCongChung auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHopDongCongChungUpdatableFieldsEquals(HopDongCongChung expected, HopDongCongChung actual) {
        assertThat(expected)
            .as("Verify HopDongCongChung relevant properties")
            .satisfies(e -> assertThat(e.getNgayLapHd()).as("check ngayLapHd").isEqualTo(actual.getNgayLapHd()))
            .satisfies(e -> assertThat(e.getNguoiLapHd()).as("check nguoiLapHd").isEqualTo(actual.getNguoiLapHd()))
            .satisfies(e -> assertThat(e.getThongTinDuongSu()).as("check thongTinDuongSu").isEqualTo(actual.getThongTinDuongSu()))
            .satisfies(e -> assertThat(e.getThongTinTaiSan()).as("check thongTinTaiSan").isEqualTo(actual.getThongTinTaiSan()))
            .satisfies(e -> assertThat(e.getThongTinVanBan()).as("check thongTinVanBan").isEqualTo(actual.getThongTinVanBan()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()))
            .satisfies(e -> assertThat(e.getIdLoaiHd()).as("check idLoaiHd").isEqualTo(actual.getIdLoaiHd()))
            .satisfies(e -> assertThat(e.getDieuKhoanHd()).as("check dieuKhoanHd").isEqualTo(actual.getDieuKhoanHd()))
            .satisfies(e -> assertThat(e.getIdDonVi()).as("check idDonVi").isEqualTo(actual.getIdDonVi()))
            .satisfies(e -> assertThat(e.getNgayThaoTac()).as("check ngayThaoTac").isEqualTo(actual.getNgayThaoTac()))
            .satisfies(e -> assertThat(e.getNguoiThaoTac()).as("check nguoiThaoTac").isEqualTo(actual.getNguoiThaoTac()))
            .satisfies(e -> assertThat(e.getIdHdGoc()).as("check idHdGoc").isEqualTo(actual.getIdHdGoc()))
            .satisfies(e ->
                assertThat(e.getThongTinChuyenNhuong()).as("check thongTinChuyenNhuong").isEqualTo(actual.getThongTinChuyenNhuong())
            )
            .satisfies(e -> assertThat(e.getMaHopDong()).as("check maHopDong").isEqualTo(actual.getMaHopDong()))
            .satisfies(e -> assertThat(e.getSrcHopDong()).as("check srcHopDong").isEqualTo(actual.getSrcHopDong()))
            .satisfies(e -> assertThat(e.getNgayHen()).as("check ngayHen").isEqualTo(actual.getNgayHen()))
            .satisfies(e -> assertThat(e.getIdSoCongChung()).as("check idSoCongChung").isEqualTo(actual.getIdSoCongChung()))
            .satisfies(e -> assertThat(e.getSoCongChung()).as("check soCongChung").isEqualTo(actual.getSoCongChung()))
            .satisfies(e -> assertThat(e.getCongChungVien()).as("check congChungVien").isEqualTo(actual.getCongChungVien()))
            .satisfies(e -> assertThat(e.getNgayKyHd()).as("check ngayKyHd").isEqualTo(actual.getNgayKyHd()))
            .satisfies(e -> assertThat(e.getNguoiRutTrich()).as("check nguoiRutTrich").isEqualTo(actual.getNguoiRutTrich()))
            .satisfies(e -> assertThat(e.getSoTienRutTrich()).as("check soTienRutTrich").isEqualTo(actual.getSoTienRutTrich()))
            .satisfies(e -> assertThat(e.getNgayRutTrich()).as("check ngayRutTrich").isEqualTo(actual.getNgayRutTrich()))
            .satisfies(e -> assertThat(e.getHdThuCong()).as("check hdThuCong").isEqualTo(actual.getHdThuCong()))
            .satisfies(e -> assertThat(e.getTrangThaiRutTrich()).as("check trangThaiRutTrich").isEqualTo(actual.getTrangThaiRutTrich()))
            .satisfies(e -> assertThat(e.getChuKyNgoaiTruSo()).as("check chuKyNgoaiTruSo").isEqualTo(actual.getChuKyNgoaiTruSo()))
            .satisfies(e -> assertThat(e.getStrSearch()).as("check strSearch").isEqualTo(actual.getStrSearch()))
            .satisfies(e -> assertThat(e.getIdMaster()).as("check idMaster").isEqualTo(actual.getIdMaster()))
            .satisfies(e -> assertThat(e.getIdHdSdHb()).as("check idHdSdHb").isEqualTo(actual.getIdHdSdHb()))
            .satisfies(e -> assertThat(e.getSrcDmMaster()).as("check srcDmMaster").isEqualTo(actual.getSrcDmMaster()))
            .satisfies(e -> assertThat(e.getRepRefUnique()).as("check repRefUnique").isEqualTo(actual.getRepRefUnique()))
            .satisfies(e -> assertThat(e.getNgayText()).as("check ngayText").isEqualTo(actual.getNgayText()))
            .satisfies(e -> assertThat(e.getNgayNum()).as("check ngayNum").isEqualTo(actual.getNgayNum()))
            .satisfies(e ->
                assertThat(e.getNgayThaoTacRutTrich()).as("check ngayThaoTacRutTrich").isEqualTo(actual.getNgayThaoTacRutTrich())
            )
            .satisfies(e -> assertThat(e.getThuLaoCongChung()).as("check thuLaoCongChung").isEqualTo(actual.getThuLaoCongChung()))
            .satisfies(e -> assertThat(e.getQuyenLaiSt()).as("check quyenLaiSt").isEqualTo(actual.getQuyenLaiSt()))
            .satisfies(e -> assertThat(e.getSoLaiSt()).as("check soLaiSt").isEqualTo(actual.getSoLaiSt()))
            .satisfies(e -> assertThat(e.getQuyenLaiTl()).as("check quyenLaiTl").isEqualTo(actual.getQuyenLaiTl()))
            .satisfies(e -> assertThat(e.getSoLaiTl()).as("check soLaiTl").isEqualTo(actual.getSoLaiTl()))
            .satisfies(e -> assertThat(e.getSrcKySoPdf()).as("check srcKySoPdf").isEqualTo(actual.getSrcKySoPdf()))
            .satisfies(e -> assertThat(e.getSrcKySoPdfSigned()).as("check srcKySoPdfSigned").isEqualTo(actual.getSrcKySoPdfSigned()))
            .satisfies(e -> assertThat(e.getSyncStatus()).as("check syncStatus").isEqualTo(actual.getSyncStatus()))
            .satisfies(e -> assertThat(e.getNgayRutTrichText()).as("check ngayRutTrichText").isEqualTo(actual.getNgayRutTrichText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHopDongCongChungUpdatableRelationshipsEquals(HopDongCongChung expected, HopDongCongChung actual) {
        // empty method
    }
}
