package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CapQuanLyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapQuanLyAllPropertiesEquals(CapQuanLy expected, CapQuanLy actual) {
        assertCapQuanLyAutoGeneratedPropertiesEquals(expected, actual);
        assertCapQuanLyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapQuanLyAllUpdatablePropertiesEquals(CapQuanLy expected, CapQuanLy actual) {
        assertCapQuanLyUpdatableFieldsEquals(expected, actual);
        assertCapQuanLyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapQuanLyAutoGeneratedPropertiesEquals(CapQuanLy expected, CapQuanLy actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapQuanLyUpdatableFieldsEquals(CapQuanLy expected, CapQuanLy actual) {
        assertThat(expected)
            .as("Verify CapQuanLy relevant properties")
            .satisfies(e -> assertThat(e.getIdCapQl()).as("check idCapQl").isEqualTo(actual.getIdCapQl()))
            .satisfies(e -> assertThat(e.getTenCapQl()).as("check tenCapQl").isEqualTo(actual.getTenCapQl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCapQuanLyUpdatableRelationshipsEquals(CapQuanLy expected, CapQuanLy actual) {
        // empty method
    }
}
