package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucCapQuanLyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucCapQuanLyAllPropertiesEquals(DanhMucCapQuanLy expected, DanhMucCapQuanLy actual) {
        assertDanhMucCapQuanLyAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucCapQuanLyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucCapQuanLyAllUpdatablePropertiesEquals(DanhMucCapQuanLy expected, DanhMucCapQuanLy actual) {
        assertDanhMucCapQuanLyUpdatableFieldsEquals(expected, actual);
        assertDanhMucCapQuanLyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucCapQuanLyAutoGeneratedPropertiesEquals(DanhMucCapQuanLy expected, DanhMucCapQuanLy actual) {
        assertThat(expected)
            .as("Verify DanhMucCapQuanLy auto generated properties")
            .satisfies(e -> assertThat(e.getIdCapQl()).as("check idCapQl").isEqualTo(actual.getIdCapQl()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucCapQuanLyUpdatableFieldsEquals(DanhMucCapQuanLy expected, DanhMucCapQuanLy actual) {
        assertThat(expected)
            .as("Verify DanhMucCapQuanLy relevant properties")
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucCapQuanLyUpdatableRelationshipsEquals(DanhMucCapQuanLy expected, DanhMucCapQuanLy actual) {
        // empty method
    }
}
