package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucQuocGiaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucQuocGiaAllPropertiesEquals(DanhMucQuocGia expected, DanhMucQuocGia actual) {
        assertDanhMucQuocGiaAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucQuocGiaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucQuocGiaAllUpdatablePropertiesEquals(DanhMucQuocGia expected, DanhMucQuocGia actual) {
        assertDanhMucQuocGiaUpdatableFieldsEquals(expected, actual);
        assertDanhMucQuocGiaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucQuocGiaAutoGeneratedPropertiesEquals(DanhMucQuocGia expected, DanhMucQuocGia actual) {
        assertThat(expected)
            .as("Verify DanhMucQuocGia auto generated properties")
            .satisfies(e -> assertThat(e.getIdQuocGia()).as("check idQuocGia").isEqualTo(actual.getIdQuocGia()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucQuocGiaUpdatableFieldsEquals(DanhMucQuocGia expected, DanhMucQuocGia actual) {
        assertThat(expected)
            .as("Verify DanhMucQuocGia relevant properties")
            .satisfies(e -> assertThat(e.getTenQuocGia()).as("check tenQuocGia").isEqualTo(actual.getTenQuocGia()))
            .satisfies(e -> assertThat(e.getTenTiengAnh()).as("check tenTiengAnh").isEqualTo(actual.getTenTiengAnh()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucQuocGiaUpdatableRelationshipsEquals(DanhMucQuocGia expected, DanhMucQuocGia actual) {
        // empty method
    }
}
