package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucDauSoCmndAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucDauSoCmndAllPropertiesEquals(DanhMucDauSoCmnd expected, DanhMucDauSoCmnd actual) {
        assertDanhMucDauSoCmndAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucDauSoCmndAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucDauSoCmndAllUpdatablePropertiesEquals(DanhMucDauSoCmnd expected, DanhMucDauSoCmnd actual) {
        assertDanhMucDauSoCmndUpdatableFieldsEquals(expected, actual);
        assertDanhMucDauSoCmndUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucDauSoCmndAutoGeneratedPropertiesEquals(DanhMucDauSoCmnd expected, DanhMucDauSoCmnd actual) {
        assertThat(expected)
            .as("Verify DanhMucDauSoCmnd auto generated properties")
            .satisfies(e -> assertThat(e.getIdDauSo()).as("check idDauSo").isEqualTo(actual.getIdDauSo()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucDauSoCmndUpdatableFieldsEquals(DanhMucDauSoCmnd expected, DanhMucDauSoCmnd actual) {
        assertThat(expected)
            .as("Verify DanhMucDauSoCmnd relevant properties")
            .satisfies(e -> assertThat(e.getDauSo()).as("check dauSo").isEqualTo(actual.getDauSo()))
            .satisfies(e -> assertThat(e.getTinhThanh()).as("check tinhThanh").isEqualTo(actual.getTinhThanh()))
            .satisfies(e -> assertThat(e.getIdLoai()).as("check idLoai").isEqualTo(actual.getIdLoai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucDauSoCmndUpdatableRelationshipsEquals(DanhMucDauSoCmnd expected, DanhMucDauSoCmnd actual) {
        // empty method
    }
}
