package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucXaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucXaAllPropertiesEquals(DanhMucXa expected, DanhMucXa actual) {
        assertDanhMucXaAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucXaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucXaAllUpdatablePropertiesEquals(DanhMucXa expected, DanhMucXa actual) {
        assertDanhMucXaUpdatableFieldsEquals(expected, actual);
        assertDanhMucXaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucXaAutoGeneratedPropertiesEquals(DanhMucXa expected, DanhMucXa actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucXaUpdatableFieldsEquals(DanhMucXa expected, DanhMucXa actual) {
        assertThat(expected)
            .as("Verify DanhMucXa relevant properties")
            .satisfies(e -> assertThat(e.getMaXa()).as("check maXa").isEqualTo(actual.getMaXa()))
            .satisfies(e -> assertThat(e.getTenXa()).as("check tenXa").isEqualTo(actual.getTenXa()))
            .satisfies(e -> assertThat(e.getMaHuyen()).as("check maHuyen").isEqualTo(actual.getMaHuyen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucXaUpdatableRelationshipsEquals(DanhMucXa expected, DanhMucXa actual) {
        // empty method
    }
}
