package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DmHuyenTmpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmHuyenTmpAllPropertiesEquals(DmHuyenTmp expected, DmHuyenTmp actual) {
        assertDmHuyenTmpAutoGeneratedPropertiesEquals(expected, actual);
        assertDmHuyenTmpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmHuyenTmpAllUpdatablePropertiesEquals(DmHuyenTmp expected, DmHuyenTmp actual) {
        assertDmHuyenTmpUpdatableFieldsEquals(expected, actual);
        assertDmHuyenTmpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmHuyenTmpAutoGeneratedPropertiesEquals(DmHuyenTmp expected, DmHuyenTmp actual) {
        assertThat(expected)
            .as("Verify DmHuyenTmp auto generated properties")
            .satisfies(e -> assertThat(e.getMaHuyen()).as("check maHuyen").isEqualTo(actual.getMaHuyen()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmHuyenTmpUpdatableFieldsEquals(DmHuyenTmp expected, DmHuyenTmp actual) {
        assertThat(expected)
            .as("Verify DmHuyenTmp relevant properties")
            .satisfies(e -> assertThat(e.getTenHuyen()).as("check tenHuyen").isEqualTo(actual.getTenHuyen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmHuyenTmpUpdatableRelationshipsEquals(DmHuyenTmp expected, DmHuyenTmp actual) {
        // empty method
    }
}
