package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DmNoiCapGpdkxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmNoiCapGpdkxAllPropertiesEquals(DmNoiCapGpdkx expected, DmNoiCapGpdkx actual) {
        assertDmNoiCapGpdkxAutoGeneratedPropertiesEquals(expected, actual);
        assertDmNoiCapGpdkxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmNoiCapGpdkxAllUpdatablePropertiesEquals(DmNoiCapGpdkx expected, DmNoiCapGpdkx actual) {
        assertDmNoiCapGpdkxUpdatableFieldsEquals(expected, actual);
        assertDmNoiCapGpdkxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmNoiCapGpdkxAutoGeneratedPropertiesEquals(DmNoiCapGpdkx expected, DmNoiCapGpdkx actual) {
        assertThat(expected)
            .as("Verify DmNoiCapGpdkx auto generated properties")
            .satisfies(e -> assertThat(e.getIdNoiCap()).as("check idNoiCap").isEqualTo(actual.getIdNoiCap()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmNoiCapGpdkxUpdatableFieldsEquals(DmNoiCapGpdkx expected, DmNoiCapGpdkx actual) {
        assertThat(expected)
            .as("Verify DmNoiCapGpdkx relevant properties")
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmNoiCapGpdkxUpdatableRelationshipsEquals(DmNoiCapGpdkx expected, DmNoiCapGpdkx actual) {
        // empty method
    }
}
