package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DmXaTmpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmXaTmpAllPropertiesEquals(DmXaTmp expected, DmXaTmp actual) {
        assertDmXaTmpAutoGeneratedPropertiesEquals(expected, actual);
        assertDmXaTmpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmXaTmpAllUpdatablePropertiesEquals(DmXaTmp expected, DmXaTmp actual) {
        assertDmXaTmpUpdatableFieldsEquals(expected, actual);
        assertDmXaTmpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmXaTmpAutoGeneratedPropertiesEquals(DmXaTmp expected, DmXaTmp actual) {
        assertThat(expected)
            .as("Verify DmXaTmp auto generated properties")
            .satisfies(e -> assertThat(e.getMaXa()).as("check maXa").isEqualTo(actual.getMaXa()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmXaTmpUpdatableFieldsEquals(DmXaTmp expected, DmXaTmp actual) {
        assertThat(expected)
            .as("Verify DmXaTmp relevant properties")
            .satisfies(e -> assertThat(e.getTenXa()).as("check tenXa").isEqualTo(actual.getTenXa()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDmXaTmpUpdatableRelationshipsEquals(DmXaTmp expected, DmXaTmp actual) {
        // empty method
    }
}
