package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DonViScanQrAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonViScanQrAllPropertiesEquals(DonViScanQr expected, DonViScanQr actual) {
        assertDonViScanQrAutoGeneratedPropertiesEquals(expected, actual);
        assertDonViScanQrAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonViScanQrAllUpdatablePropertiesEquals(DonViScanQr expected, DonViScanQr actual) {
        assertDonViScanQrUpdatableFieldsEquals(expected, actual);
        assertDonViScanQrUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonViScanQrAutoGeneratedPropertiesEquals(DonViScanQr expected, DonViScanQr actual) {
        assertThat(expected)
            .as("Verify DonViScanQr auto generated properties")
            .satisfies(e -> assertThat(e.getIdLuotQuet()).as("check idLuotQuet").isEqualTo(actual.getIdLuotQuet()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonViScanQrUpdatableFieldsEquals(DonViScanQr expected, DonViScanQr actual) {
        assertThat(expected)
            .as("Verify DonViScanQr relevant properties")
            .satisfies(e -> assertThat(e.getIdCongDan()).as("check idCongDan").isEqualTo(actual.getIdCongDan()))
            .satisfies(e -> assertThat(e.getNgayThaoTac()).as("check ngayThaoTac").isEqualTo(actual.getNgayThaoTac()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonViScanQrUpdatableRelationshipsEquals(DonViScanQr expected, DonViScanQr actual) {
        // empty method
    }
}
