package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuQuyenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuQuyenAllPropertiesEquals(MenuQuyen expected, MenuQuyen actual) {
        assertMenuQuyenAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuQuyenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuQuyenAllUpdatablePropertiesEquals(MenuQuyen expected, MenuQuyen actual) {
        assertMenuQuyenUpdatableFieldsEquals(expected, actual);
        assertMenuQuyenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuQuyenAutoGeneratedPropertiesEquals(MenuQuyen expected, MenuQuyen actual) {
        assertThat(expected)
            .as("Verify MenuQuyen auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuQuyenUpdatableFieldsEquals(MenuQuyen expected, MenuQuyen actual) {
        assertThat(expected)
            .as("Verify MenuQuyen relevant properties")
            .satisfies(e -> assertThat(e.getListMenu()).as("check listMenu").isEqualTo(actual.getListMenu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuQuyenUpdatableRelationshipsEquals(MenuQuyen expected, MenuQuyen actual) {
        // empty method
    }
}
