package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NhiemVuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhiemVuAllPropertiesEquals(NhiemVu expected, NhiemVu actual) {
        assertNhiemVuAutoGeneratedPropertiesEquals(expected, actual);
        assertNhiemVuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhiemVuAllUpdatablePropertiesEquals(NhiemVu expected, NhiemVu actual) {
        assertNhiemVuUpdatableFieldsEquals(expected, actual);
        assertNhiemVuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhiemVuAutoGeneratedPropertiesEquals(NhiemVu expected, NhiemVu actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhiemVuUpdatableFieldsEquals(NhiemVu expected, NhiemVu actual) {
        assertThat(expected)
            .as("Verify NhiemVu relevant properties")
            .satisfies(e -> assertThat(e.getIdNhiemVu()).as("check idNhiemVu").isEqualTo(actual.getIdNhiemVu()))
            .satisfies(e -> assertThat(e.getTenNhiemVu()).as("check tenNhiemVu").isEqualTo(actual.getTenNhiemVu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNhiemVuUpdatableRelationshipsEquals(NhiemVu expected, NhiemVu actual) {
        // empty method
    }
}
