package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NoiCapGtttAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoiCapGtttAllPropertiesEquals(NoiCapGttt expected, NoiCapGttt actual) {
        assertNoiCapGtttAutoGeneratedPropertiesEquals(expected, actual);
        assertNoiCapGtttAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoiCapGtttAllUpdatablePropertiesEquals(NoiCapGttt expected, NoiCapGttt actual) {
        assertNoiCapGtttUpdatableFieldsEquals(expected, actual);
        assertNoiCapGtttUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoiCapGtttAutoGeneratedPropertiesEquals(NoiCapGttt expected, NoiCapGttt actual) {
        assertThat(expected)
            .as("Verify NoiCapGttt auto generated properties")
            .satisfies(e -> assertThat(e.getIdNoiCap()).as("check idNoiCap").isEqualTo(actual.getIdNoiCap()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoiCapGtttUpdatableFieldsEquals(NoiCapGttt expected, NoiCapGttt actual) {
        assertThat(expected)
            .as("Verify NoiCapGttt relevant properties")
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNoiCapGtttUpdatableRelationshipsEquals(NoiCapGttt expected, NoiCapGttt actual) {
        // empty method
    }
}
