package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QuyenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuyenAllPropertiesEquals(Quyen expected, Quyen actual) {
        assertQuyenAutoGeneratedPropertiesEquals(expected, actual);
        assertQuyenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuyenAllUpdatablePropertiesEquals(Quyen expected, Quyen actual) {
        assertQuyenUpdatableFieldsEquals(expected, actual);
        assertQuyenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuyenAutoGeneratedPropertiesEquals(Quyen expected, Quyen actual) {
        assertThat(expected)
            .as("Verify Quyen auto generated properties")
            .satisfies(e -> assertThat(e.getIdQuyen()).as("check idQuyen").isEqualTo(actual.getIdQuyen()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuyenUpdatableFieldsEquals(Quyen expected, Quyen actual) {
        assertThat(expected)
            .as("Verify Quyen relevant properties")
            .satisfies(e -> assertThat(e.getTenQuyen()).as("check tenQuyen").isEqualTo(actual.getTenQuyen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQuyenUpdatableRelationshipsEquals(Quyen expected, Quyen actual) {
        // empty method
    }
}
